#!/bin/bash

# This file contains common functions for running MD

#==============================================================================

# Check for last run successful completion
# $1 = mdout file
# $2 = skeleton name to delete
# $3 = whether or not to return an error
#      if present, also requires mdout file is complete
# Example:
#   check_previous "Prod_1.mdout" "Prod_1"
# Deletes previous ones if error, kills self
# Creates a file called "failure" if a failure occured
function check_previous {
    if [[ -z "$3" ]]; then
        fail=1
    else
        fail=0
    fi
    error=0

    # Check for NaNs in mdinfo
    if [[ -f "mdinfo" ]]; then
        if $(grep -q "NaN" "mdinfo"); then
            echo "NaN in mdinfo!"
            error=1
        fi
    fi

    # Check for existence of mdout
    if [[ ! -f "$1" ]]; then
        echo "Mdout not found"
        error=1
    fi

    # Check that next job won't have problems with its output files
    # This is passed something where the restart exists, so that's good.
    # Usually these files exist because the job died before it could write
    # a rst.
    prefix=${2%_*}  # Eq_ or Prod_
    jobnum=${2##*_} # 02 or 14, etc

    # Handle special case with Eq_final
    # Eq_unrestrained is after Eq_final
    if [[ $jobnum == "final" ]]; then
        next="unrestrained"
    else
        next=$(( $((10#$jobnum)) + 1)) # Put it in base 10 and then add 1
    fi

    if [[ -f ${prefix}_${next}.mdout ]]; then
        echo "Removing orphan mdout file: ${prefix}_${next}.mdout"
        rm -f "${prefix}_${next}.mdout"
        error=1
    fi
    if [[ -f ${prefix}_${next}.nc ]]; then
        echo "Removing orphan trajectory file: ${prefix}_${next}.nc"
        rm -f "${prefix}_${next}.nc"
        error=1
    fi


    # Check for errors in previous trajectory
    if $(grep -q "NaN(s) found in input coordinates" "$1"); then
        echo "NaN in input coordinates"
        error=2
    # Check for Nans in mdout
    elif $(grep -q "NaN" "$1"); then
        echo "NaN in mdout!"
        error=2
    # Check for input errors in mdout
    elif $(grep -q "Input errors occurred" "$1"); then
        echo "Input errors in mdout!"
        error=2
    fi

    # Check for incomplete rst file
    # Replace error lines in slurm file so this doesn't repeatedly trigger
    badrst=$(grep "end-of-file during read" "${rev}slurm.out" | \
             tail -n 1 | awk '{print $NF}')
    if [[ ! -z $badrst ]]; then
        echo "Incomplete rst file!"
        sed -e "s/end-of-file during read/EOFERROR/g" -i "${rev}slurm.out"
        error=2
    fi

    # Check for cuda error as last line
    if $(tail -n 1 "${rev}slurm.out" | grep -qi "cuda.*gpubuffer"); then
        echo "Cuda crash!"
        error=2
    fi

    # Check for MPI error as last line
    if $(tail -n 1 "${rev}slurm.out" | grep -qi "mpi_abort"); then
        echo "MPI crash"
        error=2
    fi

    # Check for SIGABRT / posix error
    # Yeah i suck at bash today
    if $(tail -n 1 "${rev}slurm.out" | grep  -qi "Aborted"); then
       if $(grep -qi "posixio.c" "${rev}slurm.out"); then
         echo "Disk quota error."
         error=3
       fi
    fi

    if $(tail -n 1 "${rev}slurm.out" | grep -qi "Disk quota exceeded"); then
        error=3
    fi

    # Check for crash caused by previous coordinates
    # TODO

    # If requested, check mdout represents a complete file
    if [[ $fail == 1 ]] && ! $(grep -qi "Total wall time" "$1"); then
        echo "Incomplete mdout file"
        error=1
    fi

    # Delete previous one if input files are broken in some way
    if [[ "$error" -gt 1 ]]; then
        if [[ "$2" == "Prod_0" ]]; then
            echo "Deleting bad Eq_unrestrained"
            rm -f "Eq_unrestrained".{nc,mdout.rst}
            rm -f "mdinfo"

        # For final equilibration, delete symlink and its target
        elif [[ "$2" == "Eq_unrestrained" ]]; then
            echo "Deleting Eq_final"
            for ext in "mdout" "nc" "rst"; do
                rm -f "$(readlink -f Eq_final.${ext})"
                rm -f "Eq_final.${ext}"
            done

        # For heating or first equilibration, delete all heating
        elif [[ "$2" == *"Heat"* ]] || [[ $2 == Eq_1 ]]; then
            echo "Deleting heating"
            rm -f "Heat"*.{nc,mdout,rst}

        # For other equilibrations, delete the previous equilibration
        elif [[ "$2" == *"Eq"* ]]; then
            # Resolve symlink to figure out what eq_final is
            if [[ "$2" == "Eq_final" ]]; then
                prev=$(readlink "${2}.rst")
                prev=${prev%.rst}
            fi
            prev="Eq_$(($(echo "$2" | awk -F '_' '{print $NF}')-1))"
            echo "Deleting previous: $prev"
            rm -f "$prev".{nc,mdout,rst}

        else
            prev="Prod_$(($(echo "$2" | awk -F '_' '{print $NF}')-1))"
            echo "Deleting previous: $prev"
            rm -f "$prev".{nc,mdout,rst}
        fi
    fi

    if [[ "$error" -ne 0 ]]; then
        echo "Deleting $2"
        # Delete symlink targets as well
        for ext in "nc" "mdout" "rst"; do
            rm -f "$(readlink -f ${2}.${ext})"
            rm -f "$2.${ext}"
        done
        rm -f "mdinfo"

        if [[ -f "failure" ]]; then
            echo "$(($(cat "failure")+1))" > "failure"
        else
            echo "1" > "failure"
        fi

        # Error code 3 means we've hit the disk quota, hold the job
        if [[ $error -eq 3 ]]; then
            echo "Disk quota hit... holding all jobs!"
            scontrol hold Name="$SLURM_JOB_NAME"
        else
            # Resubmit the job
            sbatch --dependency=singleton "PROTOCOL.sh"
        fi
        return $fail
    fi

    rm -f "failure"
    return 0
}

#==============================================================================

# Runs a single step
# $1 = step name
# $2 = restart file
# $3 = input file. If not provided, defaults to $inpdir/$1.mdin
# $4 = if present, don't chmod output files
# Example:
#   run_md "Heat_2" "Heat_1.rst"
function run_md {
    if [[ -z $3 ]]; then
        inp="$inpdir/${1}.mdin"
    else
        inp=$3
    fi

    if [[ $SLURM_NTASKS_PER_SOCKET == 1 ]]; then
        unset CUDA_VISIBLE_DEVICES # HACK HACK HACK
        $AMBERHOME/bin/pmemd.cuda \
        -O \
        -i "$inp" \
        -o "${1}.mdout" -p "$prmtop" -c "$2" \
        -r "${1}.rst" -ref "$ref" -x "${1}.nc"
    else
        $MPI_HOME/bin/mpirun -np $SLURM_NTASKS_PER_SOCKET \
                             --bind-to socket \
                             $AMBERHOME/bin/pmemd.cuda.MPI \
                             -O \
                             -i "$inp" \
                             -o "${1}.mdout" -p "$prmtop" -c "$2" \
                             -r "${1}.rst" -ref "$ref" -x "${1}.nc" \
                             -amd "${1}.amdlog"
    fi

    # Remove write permissions but don't fail if you can't
    if [[ -z "$4" ]]; then
        set +e
        chmod a-w -f "$1".{mdout,rst,nc}
        set -e
    fi
}

#==============================================================================

# Runs a single step, on cpus only
# $1 = step name
# $2 = restart file
# $3 = input file. If not provided, defaults to $inpdir/$1.mdin
# $4 = if present, don't chmod output files
# Example:
#   run_md "Heat_2" "Heat_1.rst"
function run_md_cpu {
    if [[ -z $3 ]]; then
        inp="$inpdir/${1}.mdin"
    else
        inp=$3
    fi

    if [[ $SLURM_NTASKS == 1 ]]; then
        $AMBERHOME/bin/pmemd \
        -O \
        -i "$inp" \
        -o "${1}.mdout" -p "$prmtop" -c "$2" \
        -r "${1}.rst" -ref "$ref" -x "${1}.nc"
    else
        $MPI_HOME/bin/mpirun -np $SLURM_NTASKS \
                             --bind-to socket \
                             $AMBERHOME/bin/pmemd.MPI \
                             -O \
                             -i "$inp" \
                             -o "${1}.mdout" -p "$prmtop" -c "$2" \
                             -r "${1}.rst" -ref "$ref" -x "${1}.nc" \
                             -amd "${1}.amdlog"
    fi

    # Remove write permissions but don't fail if you can't
    if [[ -z "$4" ]]; then
        set +e
        chmod a-w -f "$1".{mdout,rst,nc}
        set -e
    fi
}

#==============================================================================

# Runs a single step, with 8 CPUs. Won't save a trajectory (for minimization)
# $1 = step name
# $2 = restart file
# $3 = input file. If not provided, defaults to $inpdir/$1.mdin
# Example:
#   run_md "min1" "init.rst" "$inpdir/01_min.mdin"
function run_md_min {
    if [[ -z $3 ]]; then
        inp="$inpdir/${1}.mdin"
    else
        inp=$3
    fi

    $MPI_HOME/bin/mpirun -np $SLURM_NTASKS \
                         --bind-to socket \
                         $AMBERHOME/bin/pmemd.MPI \
                         -O \
                         -i "$inp" \
                         -o "${1}.mdout" -p "$prmtop" -c "$2" \
                         -r "${1}.rst" -ref "$ref"
    # Remove write permissions but don't fail if you can't
    set +e
    chmod a-w -f "$1".{mdout,rst}
    set -e
}

#==============================================================================

# Prints out a summary of other things running on this node
# Hopefully this will help me debug why things are crashing all the time
function print_node_jobs {
    echo "-------------------------------"
    hn=${HOSTNAME%.local}
    echo "$hn   $(date)"
    squeue -w "$hn" -O "gres,numcpus,partition,username"
}

#==============================================================================
