#!/bin/bash
#SBATCH --time=12:00:00
#SBATCH --partition=(PART) --qos=(QOS)
#SBATCH --ntasks-per-socket=8 --tasks=8
#SBATCH --output=(REV)slurm.out --open-mode=append
#SBATCH --mail-user=robin@robinbetz.com --mail-type=ALL
#SBATCH --job-name=(NAM)_min
#
#=====================================================================
#                            PROTOCOL(REV)
#=====================================================================
# GOAL   : Minimize the system 
# INPUTS : 
# OUTPUT : 
# PROJECT: (NAM)
# PATH   : (DIR)
# DATE   : (NOW)
#=====================================================================
#

# Protocol revision number
rev=(REV)

# input files
prmtop="(PRMTOP)"
inpcrd="(INPCRD)"

# Directory with input files
inpdir="(INP)"

# Exit if any command fails
set -e

# Load necessary modules
date
module load amber/14-intel

# Minimize holding the protein really fixed and the lipid mostly fixed
echo "First minimization...of $SLURM_JOB_NAME"
mpirun -np 8 $AMBERHOME/bin/pmemd.MPI -O -i "$inpdir/01_min.mdin" -o "min1.mdout" -p "$prmtop" \
           -c "$inpcrd" -r "min1.rst" -ref "$inpcrd"

# Minimize with slightly weaker restraints
echo "Second minimization...of $SLURM_JOB_NAME"
mpirun -np 8 $AMBERHOME/bin/pmemd.MPI -O -i "$inpdir/02_min.mdin" -o "min2.mdout" -p "$prmtop" \
           -c "min1.rst" -r "min2.rst" -ref "min1.rst"

# Minimize with no restraints
echo "Third minimization...of $SLURM_JOB_NAME"
mpirun $AMBERHOME/bin/pmemd.MPI -O -i "$inpdir/03_min.mdin" -o "min3.mdout" -p "$prmtop" \
           -c "min2.rst" -r "min3.rst"

echo "Done with $SLURM_JOB_NAME"
date
