#!/bin/bash
#SBATCH --time=2:00:00
#SBATCH --partition=(PART) --qos=(QOS)
#SBATCH --tasks=8
#SBATCH --mem=4GB
#SBATCH --output=(REV)slurm.out --open-mode=append
##SBATCH --mail-user=(WHOAMI)@stanford.edu --mail-type=FAIL
#SBATCH --job-name=(NAM)_min_(REP)
#SBATCH --dependency=singleton
#
#=====================================================================
#                            PROTOCOL(REV)
#=====================================================================
# GOAL   : Minimize the system 
# INPUTS : 
# OUTPUT : 
# PROJECT: (NAM)
# PATH   : (DIR)
# DATE   : (NOW)
#=====================================================================
#

# Protocol revision number
rev=(REV)

# input files
prmtop="(PRMTOP)"
inpcrd="(INPCRD)"
ref="(REF)"

# Directory with input files
inpdir="(INP)"
cd "$inpdir"

# Exit if any command fails
set -e

# Source the common run functions
. (FUNFILE)
print_node_jobs

# Load necessary modules
source "$PI_HOME/software/amber_dev/setup_amber.sh"

# Minimize holding the protein really fixed and the lipid mostly fixed
if [[ ! -f "min_1.rst" ]]; then
    echo "First minimization...of $SLURM_JOB_NAME"
    run_md_min "min_1" "$inpcrd" "$inpdir/01_min.mdin"
fi

# Minimize with slightly weaker restraints
if [[ ! -f "min_2.rst" ]]; then
    echo "Second minimization...of $SLURM_JOB_NAME"
    check_output "$PWD" "min_1"
    run_md_min "min_2" "min_1.rst" "$inpdir/02_min.mdin" 
fi

# Minimize with restraint weight 1 on non solvent non   
if [[ ! -f "min_3.rst" ]]; then
    echo "Third minimization...of $SLURM_JOB_NAME"
    check_output "$PWD" "min_2"
    run_md_min "min_3" "min_2.rst" "$inpdir/03_min.mdin"
fi

echo "Done with $SLURM_JOB_NAME"
date

